import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/services/providers";
import { Sidebar } from "@/components/Sidebar";
import { PointsCard } from "@/components/PointsCard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex h-screen">
            {/* Left Sidebar */}
            <div className="w-1/4 h-full p-4 overflow-y-auto flex flex-col">
              <Sidebar heading="Assets" />
              <div className="mt-auto pt-4">
                <PointsCard />
              </div>
            </div>
            
            {/* Main Content */}
            <div className="w-3/4 h-full p-4">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}